export const content = [
  'AI',
  'Automated Testing',
  'Banking',
  'Education',
  'Financial Markets',
  'Financial Services',
  'Machine Learning',
  'Marketing & Advertising',
  'Mechanical or Industrial Engineering',
  'Mobile App',
  'Real Estate',
  'Trading',
  'Web',
  'Wellness and Fitness Services',
];

export const contentDE = [
  'AI',
  'Automatisierte Prüfung',
  'Bankwesen',
  'Bildung',
  'Finanzmärkte',
  'Finanzdienstleistungen',
  'Maschinelles Lernen',
  'Marketing & Werbung',
  'Maschinenbau oder Wirtschaftsingenieurwesen',
  'Mobile App',
  'Liegenschaften',
  'Handel',
  'Web',
  'Wellness- und Fitnessdienste',
];
